-- 코드를 작성해주세요
SELECT 
    ID,
    CASE
        WHEN PERCENT <= 0.25 THEN 'CRITICAL'
        WHEN PERCENT > 0.25 AND PERCENT <= 0.5 THEN 'HIGH'
        WHEN PERCENT > 0.5 AND PERCENT <= 0.75 THEN 'MEDIUM'
        WHEN PERCENT > 0.75 THEN 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT 
        ID,
        CUME_DIST() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PERCENT
    FROM ECOLI_DATA
) t
ORDER BY ID;