-- 코드를 입력하세요
SELECT
    CAR_ID, 
    ROUND(AVG(DIFF), 1) AS AVERAGE_DURATION
FROM (
    SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DIFF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) c
GROUP BY CAR_ID
HAVING AVG(DIFF) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;